### PR TITLE
Serve JSON API from canonical endpoints

### PR DESCRIPTION
**Pull request by ewdurbin**
pairs with https://github.com/pypa/warehouse/pull/11546 to serve all possible URLs for JSON API from canonicalized project name as a step towards eventually redirecting non-canonincalized URLs to the canonical ones.

### CODE REVIEW

**Review by dstufft — APPROVED** [review]
This looks right to me, but I'm not 100% confident in it.

**Comment by dstufft** [comment]
Mostly not confident in my ability to intuit what VCL is going to do without playing with it I mean :)

**Comment by cooperlees** [comment]
I feel ya! Without unit tests I'm always scared of Regex's ...

**Comment by ewdurbin** [comment]
Ope, shoulda shared the fiddle! https://fiddle.fastlydemo.net/fiddle/aef3445f

**Pull request merged**
